spring:
  application:
    name: my-bbs
  datasource:
    url: jdbc:mariadb://localhost:3307/mybbs
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

